name: entregables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate

      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 6 - Instalar dependencias
        run: pip install -r requirements.txt

      - name: Paso 7 - Ejecutar Script de prueba
        run: PYTHONPATH=src python src/edu_bigdata/main.py


      - name: Paso 8 - Crear Commit Automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización luego de pruebas de funcionamiento"
          commit_user_name: SebastianXV [GitHub Actions]
          commit_user_email: sebastian111634420@gmail.com
          commit_author: SebastianXV <sebastian111634420@gmail.com>
